[build]
builder = "NIXPACKS"

[build.nixpacksConfigOverride]
providers = ["nodejs"]

# Build commands
[build.nixpacksBuildCmd]
cmd = "npm install && npx prisma generate && npm run build"

[deploy]
# Start command
startCommand = "npm run start:prod"

# Remove health check yang bikin 502 error
# healthcheckPath = "/health"
# healthcheckTimeout = 300

# Restart policy
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Environment
numReplicas = 1
sleepApplication = false

# CRITICAL: Port configuration
[deploy.healthcheck]
path = "/"
port = 8080
interval = 30
timeout = 10
retries = 3

[environments.production]
variables = [
  "DATABASE_URL",
  "JWT_SECRET", 
  "NODE_ENV=production",
  "PORT=8080"
] 