[build]
builder = "NIXPACKS"

[build.nixpacksConfigOverride]
providers = ["nodejs"]

# Build commands
[build.nixpacksBuildCmd]
cmd = "npm install && npx prisma generate && npm run build"

[deploy]
# Start command
startCommand = "npm run start:prod"

# Health check
healthcheckPath = "/health"
healthcheckTimeout = 300

# Restart policy
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment
numReplicas = 1
sleepApplication = false

[environments.production]
variables = [
  "DATABASE_URL",
  "JWT_SECRET", 
  "NODE_ENV",
  "PORT",
  "PRISMA_CLI_BINARY_TARGETS"
] 